      - name: Download EPGs
        run: |
          curl -L \
            -H "User-Agent: Mozilla/5.0" \
            -H "Referer: https://epg.946985.filegear-sg.me/" \
            -o pp.xml \
            https://epg.112114.xyz/pp.xml

          curl -L \
            -H "User-Agent: Mozilla/5.0" \
            -H "Referer: https://epg.946985.filegear-sg.me/" \
            -o t.xml.gz \
            https://epg.946985.filegear-sg.me/t.xml.gz

          gunzip -f t.xml.gz

      - name: Merge EPG
        run: python update_epg.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add epg-all.xml
          git commit -m "Auto update epg-all.xml" || echo "No changes"
          git push
